version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  send-alerts:
    executor:
      name: python/default
      tag: 3.10.15
    steps:
      - checkout
      - run: pip install --upgrade pip
      - python/install-packages:
        pkg-manager: pip
      - run:
          command: |
            python index.py

  compute-aggregates:
    executor:
      name: python/default
      tag: 3.10.15
    steps:
      - checkout
      - run: pip install --upgrade pip
      - python/install-packages:
        pkg-manager: pip
      - run:
          command: |
            python compute_aggregates.py

  detect_volume_alerts:
    executor:
      name: python/default
      tag: 3.10.15
    steps:
      - checkout
      - run: pip install --upgrade pip
      - python/install-packages:
        pkg-manager: pip
      - run:
          command: |
            python detect_volume_alerts.py

workflows:
  send-alerts-workflow:
    triggers:
      - schedule:
          cron: "0,10,20,30,40,50 7-16 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - send-alerts

  compute-aggregates-workflow:
    triggers:
      - schedule:
          cron: "0 4 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - compute-aggregates

  detect-volume-alerts-workflow:
    triggers:
      - schedule:
          cron: "0 18 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - detect_volume_alerts
