version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  send-alerts:
    executor: python/default
    steps:
      - checkout
      - run: pip install --upgrade pip
      - python/install-packages:
        pkg-manager: pip
      - run:
          command: |
            python index.py

workflows:
  send-alerts-workflow:
    jobs:
      - send-alerts
