version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  send-alerts:
    executor:
      name: python/default
      tag: 3.10.15
    steps:
      - checkout
      - run: pip install --upgrade pip
      - python/install-packages:
        pkg-manager: pip
      - run:
          command: |
            python index.py

workflows:
  send-alerts-workflow:
    triggers:
      - schedule:
          cron: "1-59/5 7-17 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - send-alerts
